### ISSUE TITLE
NET::ERR_CERT_AUTHORITY_INVALID

### ISSUE THREAD

**Issue by mycloudedu** [ljq/gen-tlsv3-san-ca#1]
Google Chrome also prompts NET::ERR_CERT_AUTHORITY_INVALID。

![image](https://user-images.githubusercontent.com/58589942/124692976-2863cf80-df11-11eb-9220-937c503e35d4.png)

**Comment by hexabyte23** [comment]
Same for me, get this message NET::ERR_CERT_INVALID for chrome Version 95.0.4638.54

**Comment by peijs** [comment]
楼上和我得情况一下，也是这个错误。我也按照文档将CA导入到windows的证书管理中，但还谷歌浏览器还是提示不信任！！！

**Comment by ljq** [comment]
@mycloudedu Hello. In the Windows operating system, select Trusted Root Certification Authorities for the certificate storage type.（您好，如果是Windows系统环境下，安装时证书存储类型，请选择“受信任的根证书颁发机构”。）

**Comment by ljq** [comment]
@peijs Hello. In the Windows operating system, select Trusted Root Certification Authorities for the certificate storage type.（您好，如果是Windows系统环境下，安装时证书存储类型，请选择“受信任的根证书颁发机构”。）

**Comment by ljq** [comment]
@hexabyte23 Hello. In the Windows operating system, select Trusted Root Certification Authorities for the certificate storage type.（您好，如果是Windows系统环境下，安装时证书存储类型，请选择“受信任的根证书颁发机构”。）

**Comment by ljq** [comment]
Hello. In the Windows operating system, select Trusted Root Certification Authorities for the certificate storage type. Because the certificate store is automatically selected by default based on the certificate type, it is not stored and categorized to the root certificate authority. From the visa document to the trust mechanism.（您好，如果是Windows系统环境下，安装时证书存储类型，请选择“受信任的根证书颁发机构”。因为默认根据证书类型自动选择证书存储并不会存储和归类到根证书颁发机构。自签证书自信任机制。）

**Comment by peijs** [comment]
你好，我选择就是受信任的根证书颁发机构

---- Replied Message ----
| From | Jack ***@***.***> |
| Date | 08/17/2023 23:46 |
| To | ljq/gen-tlsv3-san-ca ***@***.***> |
| Cc | peijs ***@***.***>,
Mention ***@***.***> |
| Subject | Re: [ljq/gen-tlsv3-san-ca] NET::ERR_CERT_AUTHORITY_INVALID (#1) |

Hello. In the Windows operating system, select Trusted Root Certification Authorities for the certificate storage type. Because the certificate store is automatically selected by default based on the certificate type, it is not stored and categorized to the root certificate authority. From the visa document to the trust mechanism.（您好，如果是Windows系统环境下，安装时证书存储类型，请选择“受信任的根证书颁发机构”。因为默认根据证书类型自动选择证书存储并不会存储和归类到根证书颁发机构。自签证书自信任机制。）

**Comment by peijs** [comment]
测试后效果还是一样

---- Replied Message ----
| From | Jack ***@***.***> |
| Date | 08/17/2023 23:46 |
| To | ljq/gen-tlsv3-san-ca ***@***.***> |
| Cc | peijs ***@***.***>,
Mention ***@***.***> |
| Subject | Re: [ljq/gen-tlsv3-san-ca] NET::ERR_CERT_AUTHORITY_INVALID (#1) |

Hello. In the Windows operating system, select Trusted Root Certification Authorities for the certificate storage type. Because the certificate store is automatically selected by default based on the certificate type, it is not stored and categorized to the root certificate authority. From the visa document to the trust mechanism.（您好，如果是Windows系统环境下，安装时证书存储类型，请选择“受信任的根证书颁发机构”。因为默认根据证书类型自动选择证书存储并不会存储和归类到根证书颁发机构。自签证书自信任机制。）

**Comment by ljq** [comment]
@hexabyte23 @peijs @mycloudedu By the way，due to the security policy design of Firefox, you need to import the visa from the browser certificate management to the certificate authority to be trusted by the browser. （另外补充一下，因火狐浏览器的安全策略机制设计，需要从浏览器证书管理导入自签证书到证书颁发机构才能被浏览器信任，操作方式）：https://github.com/ljq/gen-tlsv3-san-ca/blob/main/images/firefox-tls.png

**Comment by ljq** [comment]
If you have any other questions, please contact author.

WeChat: labsec

Email: ljqlab@gmail.com
